name: Android Release Signed

on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build release APK
        run: bash ./gradlew assembleRelease --stacktrace
      
      - uses: zhuhaow/sign-android-release@master
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.signingKeyBase64 }}
          alias: ${{ secrets.alias }}
          keyStorePassword: ${{ secrets.keyStorePassword }}
          keyPassword: ${{ secrets.keyPassword }}

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: ${{ env.SIGNED_RELEASE_FILE }}